# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.define "abasteceAquiVM" do |abasteceAquiVM|
    abasteceAquiVM.vm.box = "ubuntu/trusty64"
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]

    chef.add_recipe "apt"
    chef.add_recipe "nodejs"
    chef.add_recipe "ruby_build"
    chef.add_recipe "vim"
    chef.add_recipe "rbenv::default"
    chef.add_recipe "heroku"
  end

  config.vm.provision "shell", path: "scripts.sh"
end

